### ISSUE TITLE
Theme does not suit well

### ISSUE THREAD

**Issue by masscream** [B00merang-Project/Windows-95#1]
My Taskbar looks like this.... 
[http://tinypic.com/r/2q19pw1/9](http://tinypic.com/r/2q19pw1/9)

And I still need to use the old version called Windows 9x through 

`gsettings set org.cinnamon.desktop.wm.preferences theme "Windows 9x"`

otherwise with the 3.8 cinnamon implementation called Windows 95, the theme appears in the Settings list but when I select it, it does not load or display on the system. The old theme works fine (except taskbar) however must be loaded through command line. Am I doing something wrong?

Running Linux Mint 19, Cinnamon 3.8.8
Thank you.

**Comment by Elbullazul** [comment]
![windows-95](https://user-images.githubusercontent.com/15310985/44733534-c8d4ec80-aab5-11e8-8d5b-193299845e6a.png)

the latest fixes should correct that. thanks for your feedback

**Comment by masscream** [comment]
Now it's perfect. Thanks a lot :-)
