### ISSUE TITLE
The text color in the panel is white

### ISSUE THREAD

**Issue by ghost** [B00merang-Project/Windows-95#2]
In Linux Mint 18 this was perfect, but after upgrading to 19, for some reason this text color in the panel changed to white. On top of a light grey background, it does not look great. Where do I change the text color to black?

![image](https://user-images.githubusercontent.com/8884429/55686726-d77c5f80-5932-11e9-94e1-4c3a7a3c59eb.png)

**Comment by Elbullazul** [comment]
There was some class changes in Cinnamon 4.x that aren't yet covered. You can try the patch from here:

https://github.com/B00merang-Project/Windows-10/issues/138

**Comment by ghost** [comment]
Thanks. Do I add those classes to cinnamon.css? I just did so and tried changing the colors from #fff/white to black, but it's still the same.

**Comment by Elbullazul** [comment]
I just tested the theme in Linux Mint 19 with cinnamon 3.8.9 and everything looked fine. What cinnamon version are you using? (Settings > System Info > Cinnamon version)

**Comment by ghost** [comment]
4.0.10

**Comment by Elbullazul** [comment]
Confirmed fixed
