### ISSUE TITLE
Whiskermenu and PulseAudio in taskbar do not render correctly on Xubuntu 18.04 LTS.

### ISSUE THREAD

**Issue by dotjax** [B00merang-Project/Windows-95#3]
![image](https://user-images.githubusercontent.com/12740958/61160090-db84c400-a4c3-11e9-8bab-262b03524e58.png)

I also notice some context menus, such as in Firefox 68, render the same way. It's a real shame because this is the closes theme to Windows 98/2000 I've ever seen.

**Comment by Elbullazul** [comment]
@mknepper what distro and Xfce version are you on?

**Comment by dotjax** [comment]
I am using Xubuntu 18.04 LTS. Xfce is 4.12.

**Comment by Elbullazul** [comment]
weird, on my VM I have a blank panel. I'll probably have to upgrade at some time.

I'll keep you updated on how work is going

**Comment by dotjax** [comment]
Awesome! If donations would help, anything I can do, I'd be glad to contribute. If I knew how theming worked, I'd do it and make a pull request or something.

**Comment by Elbullazul** [comment]
should be fixed with the last couple of Xfce fixes
